// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tcp.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求类型
type PacketType int32

const (
	PacketType_PACKET_UNKNOWN   PacketType = 0
	PacketType_PACKET_SIGN_IN   PacketType = 1
	PacketType_PACKET_MESSAGE   PacketType = 2
	PacketType_PACKET_HEARTBEAT PacketType = 3
	PacketType_PACKET_SYNC      PacketType = 4
)

var PacketType_name = map[int32]string{
	0: "PACKET_UNKNOWN",
	1: "PACKET_SIGN_IN",
	2: "PACKET_MESSAGE",
	3: "PACKET_HEARTBEAT",
	4: "PACKET_SYNC",
}

var PacketType_value = map[string]int32{
	"PACKET_UNKNOWN":   0,
	"PACKET_SIGN_IN":   1,
	"PACKET_MESSAGE":   2,
	"PACKET_HEARTBEAT": 3,
	"PACKET_SYNC":      4,
}

func (x PacketType) String() string {
	return proto.EnumName(PacketType_name, int32(x))
}

func (PacketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{0}
}

type RequestPacket struct {
	Type                 PacketType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PacketType" json:"type,omitempty"`
	Id                   int32      `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RequestPacket) Reset()         { *m = RequestPacket{} }
func (m *RequestPacket) String() string { return proto.CompactTextString(m) }
func (*RequestPacket) ProtoMessage()    {}
func (*RequestPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{0}
}

func (m *RequestPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPacket.Unmarshal(m, b)
}
func (m *RequestPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPacket.Marshal(b, m, deterministic)
}
func (m *RequestPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPacket.Merge(m, src)
}
func (m *RequestPacket) XXX_Size() int {
	return xxx_messageInfo_RequestPacket.Size(m)
}
func (m *RequestPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPacket.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPacket proto.InternalMessageInfo

func (m *RequestPacket) GetType() PacketType {
	if m != nil {
		return m.Type
	}
	return PacketType_PACKET_UNKNOWN
}

func (m *RequestPacket) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RequestPacket) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResponsePacket struct {
	Type                 PacketType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PacketType" json:"type,omitempty"`
	ReqId                int32      `protobuf:"varint,2,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Code                 int32      `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []byte     `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ResponsePacket) Reset()         { *m = ResponsePacket{} }
func (m *ResponsePacket) String() string { return proto.CompactTextString(m) }
func (*ResponsePacket) ProtoMessage()    {}
func (*ResponsePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{1}
}

func (m *ResponsePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponsePacket.Unmarshal(m, b)
}
func (m *ResponsePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponsePacket.Marshal(b, m, deterministic)
}
func (m *ResponsePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponsePacket.Merge(m, src)
}
func (m *ResponsePacket) XXX_Size() int {
	return xxx_messageInfo_ResponsePacket.Size(m)
}
func (m *ResponsePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponsePacket.DiscardUnknown(m)
}

var xxx_messageInfo_ResponsePacket proto.InternalMessageInfo

func (m *ResponsePacket) GetType() PacketType {
	if m != nil {
		return m.Type
	}
	return PacketType_PACKET_UNKNOWN
}

func (m *ResponsePacket) GetReqId() int32 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *ResponsePacket) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponsePacket) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponsePacket) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.PacketType", PacketType_name, PacketType_value)
	proto.RegisterType((*RequestPacket)(nil), "pb.RequestPacket")
	proto.RegisterType((*ResponsePacket)(nil), "pb.ResponsePacket")
}

func init() { proto.RegisterFile("tcp.proto", fileDescriptor_5d2504774879b91c) }

var fileDescriptor_5d2504774879b91c = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x9d, 0x34, 0xa9, 0xf4, 0xaa, 0x71, 0xb8, 0x28, 0x64, 0x19, 0xb2, 0x0a, 0x2e, 0xb2,
	0xd0, 0x27, 0x88, 0x25, 0xd4, 0x50, 0x1c, 0xcb, 0x24, 0x52, 0x5c, 0x85, 0xfc, 0x5c, 0xa4, 0x88,
	0x66, 0x92, 0x19, 0x17, 0x7d, 0x08, 0xdf, 0x59, 0x18, 0xed, 0xcf, 0xb6, 0xbb, 0x33, 0xe7, 0x30,
	0xe7, 0x3b, 0x5c, 0x98, 0x99, 0x56, 0x25, 0x6a, 0xec, 0x4d, 0x8f, 0x8e, 0x6a, 0xa2, 0x35, 0x5c,
	0x49, 0x1a, 0xbe, 0x49, 0x9b, 0x55, 0xdd, 0x7e, 0x90, 0xc1, 0x08, 0x5c, 0xb3, 0x55, 0x14, 0xb0,
	0x90, 0xc5, 0xfe, 0xbd, 0x9f, 0xa8, 0x26, 0xf9, 0x4b, 0xca, 0xad, 0x22, 0x69, 0x33, 0xf4, 0xc1,
	0xd9, 0x74, 0x81, 0x13, 0xb2, 0xd8, 0x93, 0xce, 0xa6, 0x43, 0x04, 0xb7, 0xab, 0x4d, 0x1d, 0x4c,
	0x42, 0x16, 0x5f, 0x4a, 0xab, 0xa3, 0x1f, 0x06, 0xbe, 0x24, 0xad, 0xfa, 0x2f, 0x4d, 0x27, 0x54,
	0xdf, 0xc2, 0x74, 0xa4, 0xa1, 0xda, 0xd7, 0x7b, 0x23, 0x0d, 0xb9, 0x25, 0xb4, 0x7d, 0x47, 0x96,
	0xe0, 0x49, 0xab, 0x31, 0x80, 0xf3, 0x4f, 0xd2, 0xba, 0x7e, 0xa7, 0xc0, 0x0d, 0x59, 0x3c, 0x93,
	0xbb, 0xe7, 0x7e, 0x8f, 0x77, 0xd8, 0x73, 0xd7, 0x03, 0x1c, 0x60, 0x88, 0xe0, 0xaf, 0xd2, 0xf9,
	0x32, 0x2b, 0xab, 0x57, 0xb1, 0x14, 0x2f, 0x6b, 0xc1, 0xcf, 0x8e, 0xbc, 0x22, 0x5f, 0x88, 0x2a,
	0x17, 0x9c, 0x1d, 0x79, 0xcf, 0x59, 0x51, 0xa4, 0x8b, 0x8c, 0x3b, 0x78, 0x03, 0xfc, 0xdf, 0x7b,
	0xca, 0x52, 0x59, 0x3e, 0x66, 0x69, 0xc9, 0x27, 0x78, 0x0d, 0x17, 0xbb, 0xdf, 0x6f, 0x62, 0xce,
	0xdd, 0x66, 0x6a, 0x8f, 0xfc, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xf7, 0xfc, 0xa0, 0x71,
	0x01, 0x00, 0x00,
}
