// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package repository

import (
	"github.com/jinzhu/gorm"
	"xim/internal/logic/repository/mysql"
)

// Injectors from wire.go:

func CreateDeviceRepository(db *gorm.DB) (Device, error) {
	deviceRepository := mysql.NewDeviceRepository(db)
	return deviceRepository, nil
}
