// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"xim/internal/logic/repository"
)

// Injectors from wire.go:

func CreateDeviceService(repo repository.Device) (DeviceService, error) {
	deviceService := NewDeviceService(repo)
	return deviceService, nil
}
