// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tcp.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 数据包类型
type PacketType int32

const (
	PacketType_UNKNOWN_PACKET PacketType = 0
	PacketType_LOGIN          PacketType = 1
	PacketType_MESSAGE        PacketType = 2
	PacketType_HEARTBEAT      PacketType = 3
	PacketType_SYNC           PacketType = 4
)

var PacketType_name = map[int32]string{
	0: "UNKNOWN_PACKET",
	1: "LOGIN",
	2: "MESSAGE",
	3: "HEARTBEAT",
	4: "SYNC",
}

var PacketType_value = map[string]int32{
	"UNKNOWN_PACKET": 0,
	"LOGIN":          1,
	"MESSAGE":        2,
	"HEARTBEAT":      3,
	"SYNC":           4,
}

func (x PacketType) String() string {
	return proto.EnumName(PacketType_name, int32(x))
}

func (PacketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{0}
}

// app 类型
type App int32

const (
	App_UNKNOWN_APP App = 0
	App_ANDROID     App = 1
	App_IOS         App = 2
	App_WIN         App = 3
	App_LINUX       App = 4
)

var App_name = map[int32]string{
	0: "UNKNOWN_APP",
	1: "ANDROID",
	2: "IOS",
	3: "WIN",
	4: "LINUX",
}

var App_value = map[string]int32{
	"UNKNOWN_APP": 0,
	"ANDROID":     1,
	"IOS":         2,
	"WIN":         3,
	"LINUX":       4,
}

func (x App) String() string {
	return proto.EnumName(App_name, int32(x))
}

func (App) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{1}
}

type LoginReq struct {
	App                  App      `protobuf:"varint,1,opt,name=app,proto3,enum=pb.App" json:"app,omitempty"`
	DeviceId             int64    `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetApp() App {
	if m != nil {
		return m.App
	}
	return App_UNKNOWN_APP
}

func (m *LoginReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *LoginReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Text struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Text) Reset()         { *m = Text{} }
func (m *Text) String() string { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()    {}
func (*Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{1}
}

func (m *Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Text.Unmarshal(m, b)
}
func (m *Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Text.Marshal(b, m, deterministic)
}
func (m *Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Text.Merge(m, src)
}
func (m *Text) XXX_Size() int {
	return xxx_messageInfo_Text.Size(m)
}
func (m *Text) XXX_DiscardUnknown() {
	xxx_messageInfo_Text.DiscardUnknown(m)
}

var xxx_messageInfo_Text proto.InternalMessageInfo

func (m *Text) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Image struct {
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{2}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// 消息
type Message struct {
	// Types that are valid to be assigned to Content:
	//	*Message_Text
	//	*Message_Image
	Content              isMessage_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{3}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Content interface {
	isMessage_Content()
}

type Message_Text struct {
	Text *Text `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Message_Image struct {
	Image *Image `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

func (*Message_Text) isMessage_Content() {}

func (*Message_Image) isMessage_Content() {}

func (m *Message) GetContent() isMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Message) GetText() *Text {
	if x, ok := m.GetContent().(*Message_Text); ok {
		return x.Text
	}
	return nil
}

func (m *Message) GetImage() *Image {
	if x, ok := m.GetContent().(*Message_Image); ok {
		return x.Image
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_Text)(nil),
		(*Message_Image)(nil),
	}
}

type RequestPacket struct {
	Type                 PacketType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PacketType" json:"type,omitempty"`
	Id                   int32      `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RequestPacket) Reset()         { *m = RequestPacket{} }
func (m *RequestPacket) String() string { return proto.CompactTextString(m) }
func (*RequestPacket) ProtoMessage()    {}
func (*RequestPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{4}
}

func (m *RequestPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPacket.Unmarshal(m, b)
}
func (m *RequestPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPacket.Marshal(b, m, deterministic)
}
func (m *RequestPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPacket.Merge(m, src)
}
func (m *RequestPacket) XXX_Size() int {
	return xxx_messageInfo_RequestPacket.Size(m)
}
func (m *RequestPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPacket.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPacket proto.InternalMessageInfo

func (m *RequestPacket) GetType() PacketType {
	if m != nil {
		return m.Type
	}
	return PacketType_UNKNOWN_PACKET
}

func (m *RequestPacket) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RequestPacket) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResponsePacket struct {
	Type                 PacketType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.PacketType" json:"type,omitempty"`
	ReqId                int32      `protobuf:"varint,2,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Code                 int32      `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Data                 []byte     `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ResponsePacket) Reset()         { *m = ResponsePacket{} }
func (m *ResponsePacket) String() string { return proto.CompactTextString(m) }
func (*ResponsePacket) ProtoMessage()    {}
func (*ResponsePacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2504774879b91c, []int{5}
}

func (m *ResponsePacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponsePacket.Unmarshal(m, b)
}
func (m *ResponsePacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponsePacket.Marshal(b, m, deterministic)
}
func (m *ResponsePacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponsePacket.Merge(m, src)
}
func (m *ResponsePacket) XXX_Size() int {
	return xxx_messageInfo_ResponsePacket.Size(m)
}
func (m *ResponsePacket) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponsePacket.DiscardUnknown(m)
}

var xxx_messageInfo_ResponsePacket proto.InternalMessageInfo

func (m *ResponsePacket) GetType() PacketType {
	if m != nil {
		return m.Type
	}
	return PacketType_UNKNOWN_PACKET
}

func (m *ResponsePacket) GetReqId() int32 {
	if m != nil {
		return m.ReqId
	}
	return 0
}

func (m *ResponsePacket) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponsePacket) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponsePacket) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.PacketType", PacketType_name, PacketType_value)
	proto.RegisterEnum("pb.App", App_name, App_value)
	proto.RegisterType((*LoginReq)(nil), "pb.LoginReq")
	proto.RegisterType((*Text)(nil), "pb.Text")
	proto.RegisterType((*Image)(nil), "pb.Image")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*RequestPacket)(nil), "pb.RequestPacket")
	proto.RegisterType((*ResponsePacket)(nil), "pb.ResponsePacket")
}

func init() { proto.RegisterFile("tcp.proto", fileDescriptor_5d2504774879b91c) }

var fileDescriptor_5d2504774879b91c = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x6f, 0x9b, 0x40,
	0x10, 0x35, 0x5f, 0xc1, 0x8c, 0x1b, 0xba, 0x1a, 0xb5, 0xaa, 0xd3, 0x4a, 0x95, 0xcb, 0xc9, 0xca,
	0xc1, 0x07, 0xf7, 0x0f, 0x94, 0x24, 0x28, 0x46, 0x49, 0xb0, 0xbb, 0x26, 0x72, 0x7b, 0xb2, 0x30,
	0x8c, 0x22, 0x94, 0x06, 0x16, 0x58, 0x57, 0xc9, 0x8f, 0xe8, 0x7f, 0xae, 0x76, 0x71, 0x92, 0x5e,
	0x7b, 0x7b, 0x33, 0x8f, 0x79, 0xef, 0xf1, 0xb4, 0xe0, 0xc9, 0x5c, 0xcc, 0x44, 0x5b, 0xcb, 0x1a,
	0x4d, 0xb1, 0x0b, 0x1a, 0x18, 0x5e, 0xd7, 0x77, 0x65, 0xc5, 0xa9, 0xc1, 0x13, 0xb0, 0x32, 0x21,
	0xc6, 0xc6, 0xc4, 0x98, 0xfa, 0x73, 0x77, 0x26, 0x76, 0xb3, 0x50, 0x08, 0xae, 0x76, 0xf8, 0x09,
	0xbc, 0x82, 0x7e, 0x97, 0x39, 0x6d, 0xcb, 0x62, 0x6c, 0x4e, 0x8c, 0xa9, 0xc5, 0x87, 0xfd, 0x22,
	0x2e, 0xf0, 0x03, 0xb8, 0xfb, 0x8e, 0x5a, 0x45, 0x59, 0x9a, 0x3a, 0x52, 0x63, 0x5c, 0xe0, 0x3b,
	0x70, 0x64, 0x7d, 0x4f, 0xd5, 0xd8, 0x9e, 0x18, 0x53, 0x8f, 0xf7, 0x43, 0xf0, 0x11, 0xec, 0x94,
	0x1e, 0x25, 0x22, 0xd8, 0x92, 0x1e, 0xa5, 0xf6, 0xf3, 0xb8, 0xc6, 0xc1, 0x09, 0x38, 0xf1, 0x43,
	0x76, 0x47, 0xc8, 0xc0, 0xda, 0xb7, 0xbf, 0x0e, 0x87, 0x0a, 0x06, 0x1b, 0x70, 0x6f, 0xa8, 0xeb,
	0x14, 0xf9, 0xf9, 0x9f, 0xcb, 0xd1, 0x7c, 0xa8, 0x92, 0x2a, 0xc5, 0xc5, 0xa0, 0x57, 0xc1, 0x2f,
	0xe0, 0x94, 0x4a, 0x45, 0x27, 0x1d, 0xcd, 0x3d, 0xf5, 0x81, 0x96, 0x5d, 0x0c, 0x78, 0xcf, 0x9c,
	0x79, 0xe0, 0xe6, 0x75, 0x25, 0xa9, 0x92, 0xc1, 0x06, 0x8e, 0x39, 0x35, 0x7b, 0xea, 0xe4, 0x2a,
	0xcb, 0xef, 0x49, 0x62, 0x00, 0xb6, 0x7c, 0x12, 0x74, 0x28, 0xc2, 0x57, 0xd7, 0x3d, 0x93, 0x3e,
	0x09, 0xe2, 0x9a, 0x43, 0x1f, 0xcc, 0x43, 0x13, 0x0e, 0x37, 0xcb, 0x42, 0xfd, 0x4c, 0x91, 0xc9,
	0x4c, 0x17, 0xf0, 0x86, 0x6b, 0x1c, 0xfc, 0x31, 0xc0, 0xe7, 0xd4, 0x89, 0xba, 0xea, 0xe8, 0x3f,
	0xa4, 0xdf, 0xc3, 0x51, 0x4b, 0xcd, 0xf6, 0x45, 0xde, 0x69, 0xa9, 0x89, 0xb5, 0x43, 0x5e, 0x17,
	0xa4, 0x1d, 0x1c, 0xae, 0x31, 0x8e, 0xc1, 0x7d, 0xe8, 0x3b, 0x39, 0x34, 0xf5, 0x3c, 0xbe, 0xe4,
	0x71, 0x5e, 0xf3, 0x9c, 0x7e, 0x07, 0x78, 0x35, 0x43, 0x04, 0xff, 0x36, 0xb9, 0x4a, 0x96, 0x9b,
	0x64, 0xbb, 0x0a, 0xcf, 0xaf, 0xa2, 0x94, 0x0d, 0xd0, 0x03, 0xe7, 0x7a, 0x79, 0x19, 0x27, 0xcc,
	0xc0, 0x11, 0xb8, 0x37, 0xd1, 0x7a, 0x1d, 0x5e, 0x46, 0xcc, 0xc4, 0x63, 0xf0, 0x16, 0x51, 0xc8,
	0xd3, 0xb3, 0x28, 0x4c, 0x99, 0x85, 0x43, 0xb0, 0xd7, 0x3f, 0x93, 0x73, 0x66, 0x9f, 0x7e, 0x03,
	0x2b, 0x14, 0x02, 0xdf, 0xc2, 0xe8, 0x59, 0x2b, 0x5c, 0xad, 0xd8, 0x40, 0x5d, 0x87, 0xc9, 0x05,
	0x5f, 0xc6, 0x17, 0xcc, 0x40, 0x17, 0xac, 0x78, 0xb9, 0x66, 0xa6, 0x02, 0x9b, 0x38, 0x61, 0x96,
	0xf6, 0x89, 0x93, 0xdb, 0x1f, 0xcc, 0xde, 0x1d, 0xe9, 0xb7, 0xf8, 0xf5, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf5, 0xfa, 0x5c, 0x0b, 0x98, 0x02, 0x00, 0x00,
}
